### ISSUE TITLE
Expand list of "well-known" parsers.

### ISSUE THREAD

**Issue by YegorUdovchenko** [SpineEventEngine/web#131]
Currently, `spine-web` JavaScript client requires custom Protobuf message types and parsers to be passed for client initialization. Some of "well-known" parsers are built-in and defined in `web/client-js/main/client/parser/well-known-parsers.js`. The issue is to expand the list of those parsers with parser for `google.protobuf.Struct` type.

**Comment by armiol** [comment]
@YegorUdovchenko Apparently, this issue was addressed via #132 in version `1.4.2`.

Please confirm that you no longer experience the issue.

**Comment by YegorUdovchenko** [comment]
Works well, thank you.
