### ISSUE TITLE
`BackendClient.fetchAll` method: a notification for receiving the entire requested collection is needed

### ISSUE THREAD

**Issue by dpikhulya** [SpineEventEngine/web#2]
### The Problem

The [`BackendClient.fetchAll()`](https://github.com/SpineEventEngine/web/blob/ce09f64740a6496167798cc04acd104a4ebe2b9f/client-js/src/client/backend-client.js#L55) method currently provides the requested collection through a callback that receives one item from the resulting collection at a time (see the [`dataCallback`](https://github.com/SpineEventEngine/web/blob/ce09f64740a6496167798cc04acd104a4ebe2b9f/client-js/src/client/backend-client.js#L55) parameter). 

The problem is that there currently doesn't seem to be a way for the invoker of this method to detect that the entire requested collection has been supplied, and no more item callbacks will be invoked for this request. 

This issue is to extend the `BackendClient.fetchAll()` method to provide such a notification (in addition to the existing per-item callback, which might still be useful in some scenarios). It would be useful if this notification provided the entire collection of items in some of its parameters.

### Use cases

In particular, we need this for implementing the following functionality in Web client applications:
- We need to display the "Loading in progress" indicator when issuing a request, and we need this callback to hide it when all items have been read.
- If we're visiting a page that displays a list of some entities that is currently empty, we need this callback to understand that no items will be delivered in order to display a message like "No items found" for the user.

### Possible API

Preliminarily, since there is only one error callback in this method, we could rework this method to be like this:
```
/**
 * @param type ...
 * @param {function(Object)=} singleItemCallback
 * @returns {Promise}
 */
fetchAll(type, singleItemCallback = undefined): Promise
```
In this API, `singleItemCallback` still works as the current `dataCallback` (receives items one by one), but it is optional. Besides, the method returns a `Promise` instance that is fulfilled with an entire collection as a parameter when all of the requested items were received, and rejected if an error has occurred (we can supposedly reject it instead of invoking the [`errorCallback`](https://github.com/SpineEventEngine/web/blob/ce09f64740a6496167798cc04acd104a4ebe2b9f/client-js/src/client/backend-client.js#L55) that is currently passed as a parameter).

### Possible Implementation

Seems that Firebase's `once('value')` event listener should provide us with a notification that we need (which reportedly contains all of the requested data), if the respective entry with the entire collection is created transactionally on the backend. 

See the ["Listen for value events"](https://firebase.google.com/docs/database/web/lists-of-data#listen_for_value_events) section in Freibase documentation for the description of this event.

Besides, what we've found when trying to listen for the `'value'` event like this for the investigation purposes, it appears that the backend doesn't create the respective request/response Firebase entry if the requested list of entities is empty, so we naturally never received the `'value'` event in such cases, and this particular case of empty collections should likely be fixed as well.

**Comment by mdrachuk** [comment]
This was implemented in PR https://github.com/SpineEventEngine/web/pull/12.
