### ISSUE TITLE
Allow overriding HTTP client of a Spine Web JavaScript client.

### ISSUE THREAD

**Issue by YegorUdovchenko** [SpineEventEngine/web#207]
The current version of a Spine Web client for JavaScript provides a high-level API for interacting with a Spine-based backend and carries all HTTP-related functionality. It makes tricky to:
 - add custom HTTP headers, e.g. "Authorization";
 - use non-CORS request mode;
 - expand client to interact with custom backend endpoints (non "/command" or "/query" ) that use similar protocol, e.i. Protobuf request/response body and the same set of auth headers;

To solve above-mentioned issues in Pure Photos we use our custom implementation of `HttpClient` and inject it after Spine Web client instantiation.

**Comment by armiol** [comment]
@YegorUdovchenko I am not sure whether this is an old issue, or a new one. But just in case: #194.

**Comment by armiol** [comment]
It's been released with [1.9.0](https://github.com/SpineEventEngine/web/releases/tag/v1.9.0).

**Comment by YegorUdovchenko** [comment]
> @YegorUdovchenko I am not sure whether this is an old issue, or a new one. But just in case: #194.

Sorry, missed this update.
