### ISSUE TITLE
Reconsider the approach of defining the `HttpServletRequest` content type

### ISSUE THREAD

**Issue by YegorUdovchenko** [SpineEventEngine/web#23]
The current implementation of the [MessageFormat.formatOf()](https://github.com/SpineEventEngine/web/blob/f3373f6f9d3eb56bd6df1a317f3fcdf273cad352/web/src/main/java/io/spine/web/parser/MessageFormat.java#L88) compares the "Content-Type" header of the passed request with one of predefined MIME-types ("application/json", "application/x-protobuf") without considering of a charset value. In consequence of that, it can`t recognize the passed request with a content type of "application/json; charset=utf-8" as a JSON message format. 

As a solution, the simple string values of the stringification format could be replaced with Guava [MediaType](https://github.com/google/guava/blob/master/guava/src/com/google/common/net/MediaType.java) values.

**Comment by mdrachuk** [comment]
Implemented in PR #24.
