### ISSUE TITLE
Reconsider the approach to the formation of errors given by the `spine-web-client`

### ISSUE THREAD

**Issue by YegorUdovchenko** [SpineEventEngine/web#26]
The current `spine-web-client` implementation provides the single class for all errors to be returned to the client. It is represented with [`EndpointError`](https://github.com/SpineEventEngine/web/blob/7324602c4b037d840e9d35b85e4c80f853e3bf33/client-js/src/client/http-endpoint.js#L27) class.

The approach with having a single error class for all types of errors complicates their processing on the client side. It would be better to have a hierarchy of errors (server, client and connection errors) instead of calling `isConnection()`, `isServer()`, `isClient()` methods and retrieving parameters specific to the error kind.

**Comment by mdrachuk** [comment]
Implemented in [PR #34: Introduce `spine-web-client` error hierarchy](https://github.com/SpineEventEngine/web/pull/34).
