### ISSUE TITLE
Connection errors are not handled in `spine-web-client`

### ISSUE THREAD

**Issue by YegorUdovchenko** [SpineEventEngine/web#27]
When a web-application that uses `spine-web-client` loses internet connection, the unhandled exception is thrown on each request. This situation should be handled and returned to the client in a controlled way as a connection error.

The current implementation of [`HttpClient`](https://github.com/SpineEventEngine/web/blob/7324602c4b037d840e9d35b85e4c80f853e3bf33/client-js/src/client/http-client.js#L33) does not handle connection errors.  Its [`postMessage(endpoint, message)`](https://github.com/SpineEventEngine/web/blob/7324602c4b037d840e9d35b85e4c80f853e3bf33/client-js/src/client/http-client.js#L54) expects that each request will result in a response, which is wrong when a connection error occurs.

Request to change the approach of errors classification is described in associated issue [https://github.com/SpineEventEngine/web/issues/26](https://github.com/SpineEventEngine/web/issues/26)

**Comment by mdrachuk** [comment]
Implemented in [PR #34: Introduce `spine-web-client` error hierarchy](https://github.com/SpineEventEngine/web/pull/34).
