### ISSUE TITLE
Add support for adding subscriptions for data changes

### ISSUE THREAD

**Issue by dpikhulya** [SpineEventEngine/web#3]
### The Problem

The `BackendClient` class currently only supports fetching the snapshots of the current state of requested data (see the [`fetchAll`](https://github.com/SpineEventEngine/web/blob/ce09f64740a6496167798cc04acd104a4ebe2b9f/client-js/src/client/backend-client.js#L55) and [`fetchById`](https://github.com/SpineEventEngine/web/blob/ce09f64740a6496167798cc04acd104a4ebe2b9f/client-js/src/client/backend-client.js#L69) methods). 

What we need in addition to this is to add subscriptions for the same pieces of data (all items by type, and one item by id), so that the user of `spine-js-client` could receive notifications when the data that is being subscribed to changes.

Preliminarily, when subscribing to collection changes, we might receive the following kinds of notifications:
- _"Item added"_.
- _"Item changed"_.
- _"Item removed"_.
- Possibly, if order of items can ever be controlled in queries, _"Item moved"_.

### Use Cases

This feature can be used for implementing use cases like these in Web UI:
- A users visits a page with a list of entities, stays on that page, and needs to see the up-to-date information when other users update this list on their own workstations.
- A user opens some entity for viewing and needs to see any data updates that other users make to this entity while it is open.
  - Same for (long-time) editing of an entity — it might be be helpful to know that another user has edited this entity while the user was editing it.

### A Possible API

Here's what such API can look like:
```
/**
 * @param {TypeUrl} typeUrl
 * @returns EntitiesSubscription
 */
subscribeToAll(typeUrl)

/**
 * @param {TypeUrl} typeUrl
 * @param {TypedMessage} id
 * @returns EntitySubscription
 */
subscribeById(typeUrl, id)
```

```
class EntitiesSubscription {
  /**
   * @param {function(Object???)} handler
   *           (we might also need to identify a place in a list where an item is inserted, 
   *           if we respect the order of items in our fetches/queries, see also `onItemMoved` 
   *           below)
   */
  onItemAdded(handler)

  /**
   * @param {function(Object???)} handler  
   *           a function that is passed an entity that was modified (a new version of the entity
   *           is passed here)
   */
  onItemChanged(handler)
 
  /**
   * @param {function(Object)} handler  
   *           a function that is passed an entity that (hash?) was removed
   */
  onItemRemoved(handler)

  /**
   * (optional, depending on whether we're going to respect items order in our queries)
   *
   * @param {function(Object, Number(???how will we define a place in a collection))} handler
   */
  onItemMoved(handler)
}
```

```
class EntitySubscription {
  /**
   * @param {function(Object)} handler  
   *           an updated version of the respective entity
   */
  onChanged(handler)

  /**
   * @param {function(Object ???see below??? )} handler  
   *     (we might not have to implement passing the removed object into the removal callback,
   *     since the one adding a subscription should already know what entity is being subscribed to,
   *     but seems it might still be generally useful, e.g. to be able to attach the same callback to
   *     different entities, if needed, so we might consider implementing it, if it is technically possible)
   */
  onRemoved(handler)
}
```
Some things that might need to be thought about during the implementation:
- Not sure whether any error notifications could also be present here.
- Besides, not sure whether any close/dispose/cleanup functionality should be added for subscriptions (whether it is technically needed for an actual subscriptions implementation).

The usage of such an API can be like this:
```
  const licensesSubscription = backendClient.subscribeToAll(commercialLicensesTypeURL);
  licensesSubscription.onItemAdded(license => { ... } );
  licensesSubscription.onItemChanged(license => { ... } );
  licensesSubscription.onItemRemoved(license => { ... } );
  licensesSubscription.onItemMoved(license => { ... } );
```
or like this for single entity subscriptions:
```
  const taskSubscription = backendClient.subscribeById(taskTypeURL, taskId);
  taskSubscription.onChanged(task => { ... });
  taskSubscription.onRemoved(task => { ... });
```

### A Possible Implementation 

Not sure whether there's any existing mechanism for this already prepared, but here's just a quick observation that Firebase provides notifications for child updates that seem to align with the list updates functionality that we need. See the ["Listen for child events"](https://firebase.google.com/docs/database/web/lists-of-data#listen_for_child_events) section here.

**Comment by mdrachuk** [comment]
Implemented in https://github.com/SpineEventEngine/web/pull/20.
