### ISSUE TITLE
`BackendClient.sendCommand` method's rejection callback is not invoked

### ISSUE THREAD

**Issue by YegorUdovchenko** [SpineEventEngine/web#6]
The [`BackendClient.sendCommand()`](https://github.com/SpineEventEngine/web/blob/ce09f64740a6496167798cc04acd104a4ebe2b9f/client-js/src/client/backend-client.js#L84) currently provides the functionality of sending commands with an acknowledgment of a successful delivery and errors occurrence:  

- The parameterless `successListener`  is called if no transport errors occurred and the command message meets the validation requirements.
- The `errorCallback` is called on transport errors, command message validation errors and server runtime errors. 

The `rejectionCallback` that can be passed to `sendCommand` as a [parameter](https://github.com/SpineEventEngine/web/blob/ce09f64740a6496167798cc04acd104a4ebe2b9f/client-js/src/client/backend-client.js#L87) is not invoked currently though.

This issue is to complete/fix the `BackendClient.sendCommand()` method's functionality so that a rejection callback works as designed.

**Comment by armiol** [comment]
@dmitrykuzmin please have a look. I think this issue is either obsolete or done.

**Comment by dmitrykuzmin** [comment]
The ability to pass this callback is still present in the new Client API.

In theory, it can be invoked - when the client app implements a custom filter which rejects the command not with `Error` but with a `RejectionMessage`. But I don't really know if it's a valid use case. Standard Spine filters never do that.

This issue, I guess, was originally about callback not being invoked after command _leads_ to a rejection. As we can now `observe` the events/rejections produced by the command, it's better, in my opinion, to drop the support for this callback altogether.

**Comment by armiol** [comment]
@dmitrykuzmin let's schedule the removal of this callback and stick with the observation only.
