### ISSUE TITLE
Detect and fix vulnerabilities in NPM dependencies

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/web#74]
At the moment during the build we get

```
found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

We need to fail the build in case of any vulnerabilities found automatically.

Those found currently need to be addressed.

**Comment by YegorUdovchenko** [comment]
Addressed in https://github.com/SpineEventEngine/web/pull/77
