### ISSUE TITLE
Deal with two `testJs` tasks

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/web#75]
There are two `testJs` Gradle tasks in the project. One declared in `scripts/js.gradle`, another one coming from the `config/gradle/js/build-tasks.gradle`.

To get the machine running, the "local" one has been renamed to `testLibraryJs`. But still something does not feel right.

**Comment by YegorUdovchenko** [comment]
Addressed in https://github.com/SpineEventEngine/web/pull/77
