### ISSUE TITLE
Get rid of Protobuf configuration

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/web#94]
Currently, we customize the Protobuf generation paths for JS code gen.

When ProtoJsPlugin is set up to support custom paths, we should remove the `protobuf {}` closure in `client-js/build.gradle`.

**Comment by armiol** [comment]
@dmdashenkov you have done some work on the path resolution recently. Is this issue resolved?

**Comment by dmdashenkov** [comment]
Seems to be resolved now.
